//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawManhwa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comic()
        {
            this.DetailComics = new HashSet<DetailComic>();
            this.HistoryReadComicOfUsers = new HashSet<HistoryReadComicOfUser>();
            this.ListOfComicsUsersFollows = new HashSet<ListOfComicsUsersFollow>();
        }
    
        public int Id { get; set; }
        public string NameComic { get; set; }
        public string DifferentNameComic { get; set; }
        public int ViewCount { get; set; }
        public string UrlCoverImageComic { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IdNewChapter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailComic> DetailComics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryReadComicOfUser> HistoryReadComicOfUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOfComicsUsersFollow> ListOfComicsUsersFollows { get; set; }
    }
}
