//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawManhwa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComicEntities : DbContext
    {
        public ComicEntities()
            : base("name=ComicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AppRoleClaim> AppRoleClaims { get; set; }
        public virtual DbSet<AppRole> AppRoles { get; set; }
        public virtual DbSet<AppUserClaim> AppUserClaims { get; set; }
        public virtual DbSet<AppUserLogin> AppUserLogins { get; set; }
        public virtual DbSet<AppUserRole> AppUserRoles { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<AppUserToken> AppUserTokens { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChapterComic> ChapterComics { get; set; }
        public virtual DbSet<Comic> Comics { get; set; }
        public virtual DbSet<DetailCategory> DetailCategories { get; set; }
        public virtual DbSet<DetailComic> DetailComics { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<HistoryReadComicOfUser> HistoryReadComicOfUsers { get; set; }
        public virtual DbSet<ListOfComicsUsersFollow> ListOfComicsUsersFollows { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<UrlImageComic> UrlImageComics { get; set; }
    }
}
